-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./extensions/CollisionManager/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/collision_title (
  ct_page INTEGER UNSIGNED NOT NULL,
  ct_namespace INTEGER NOT NULL,
  ct_title BLOB DEFAULT '' NOT NULL,
  ct_rules CLOB DEFAULT '' NOT NULL,
  ct_state CLOB DEFAULT '' NOT NULL,
  ct_search BLOB DEFAULT '' NOT NULL,
  PRIMARY KEY(ct_page)
);

CREATE UNIQUE INDEX ct_page ON /*_*/collision_title (ct_page);

CREATE INDEX ct_namespace_title ON /*_*/collision_title (ct_namespace, ct_title);

CREATE INDEX ct_namespace_search ON /*_*/collision_title (ct_namespace, ct_search);
