-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./extensions/CollisionManager/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/collision_title (
  ct_page INT UNSIGNED NOT NULL,
  ct_namespace INT NOT NULL,
  ct_title VARBINARY(255) DEFAULT '' NOT NULL,
  ct_rules TEXT NOT NULL,
  ct_state TEXT NOT NULL,
  ct_search VARBINARY(255) DEFAULT '' NOT NULL,
  UNIQUE INDEX ct_page (ct_page),
  INDEX ct_namespace_title (ct_namespace, ct_title),
  INDEX ct_namespace_search (ct_namespace, ct_search),
  PRIMARY KEY(ct_page)
) /*$wgDBTableOptions*/;
