-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./extensions/CollisionManager/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE collision_title (
  ct_page INT NOT NULL,
  ct_namespace INT NOT NULL,
  ct_title TEXT DEFAULT '' NOT NULL,
  ct_rules TEXT DEFAULT '' NOT NULL,
  ct_state TEXT DEFAULT '' NOT NULL,
  ct_search TEXT DEFAULT '' NOT NULL,
  PRIMARY KEY(ct_page)
);

CREATE UNIQUE INDEX ct_page ON collision_title (ct_page);

CREATE INDEX ct_namespace_title ON collision_title (ct_namespace, ct_title);

CREATE INDEX ct_namespace_search ON collision_title (ct_namespace, ct_search);
